# Generated by Django 3.2.13 on 2022-06-16 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220616_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipe',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='units',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ingredients'),
        ),
    ]
