# Generated by Django 3.2.13 on 2022-06-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220616_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
