# Generated by Django 3.2.13 on 2022-06-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220616_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': 'Ingredients'},
        ),
    ]
