# Generated by Django 3.2.13 on 2022-06-27 14:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
