# Generated by Django 3.2.13 on 2022-06-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
