# Generated by Django 3.2.13 on 2022-06-22 17:49

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ingredient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='other_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[home.validators.validate_unit_of_measure]),
        ),
    ]
