# Generated by Django 3.2.13 on 2022-07-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220701_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
