# Generated by Django 3.2.13 on 2022-07-03 11:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatarplaceholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
