# Generated by Django 3.2.13 on 2022-07-03 11:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='v1656845904/chef_dvaqcl.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
