# Generated by Django 3.2.13 on 2022-07-03 15:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='v1656845904/chef_dvaqcl.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
