# Generated by Django 3.2.13 on 2022-07-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20220704_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
    ]
