# Generated by Django 3.2.13 on 2022-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20220707_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.TextField(default='ici', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='introduction',
            field=models.TextField(blank=True, default='ici', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(default='ici', null=True),
        ),
    ]
